/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateProbaArgs } from "./CreateProbaArgs";
import { UpdateProbaArgs } from "./UpdateProbaArgs";
import { DeleteProbaArgs } from "./DeleteProbaArgs";
import { ProbaFindManyArgs } from "./ProbaFindManyArgs";
import { ProbaFindUniqueArgs } from "./ProbaFindUniqueArgs";
import { Proba } from "./Proba";
import { ProbaService } from "../proba.service";

@graphql.Resolver(() => Proba)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ProbaResolverBase {
  constructor(
    protected readonly service: ProbaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Proba",
    action: "read",
    possession: "any",
  })
  async _probasMeta(
    @graphql.Args() args: ProbaFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Proba])
  @nestAccessControl.UseRoles({
    resource: "Proba",
    action: "read",
    possession: "any",
  })
  async probas(
    @graphql.Args() args: ProbaFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Proba[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Proba",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Proba, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Proba",
    action: "read",
    possession: "own",
  })
  async proba(
    @graphql.Args() args: ProbaFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Proba | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Proba",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Proba)
  @nestAccessControl.UseRoles({
    resource: "Proba",
    action: "create",
    possession: "any",
  })
  async createProba(
    @graphql.Args() args: CreateProbaArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Proba> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Proba",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Proba"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Proba)
  @nestAccessControl.UseRoles({
    resource: "Proba",
    action: "update",
    possession: "any",
  })
  async updateProba(
    @graphql.Args() args: UpdateProbaArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Proba | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Proba",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Proba"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Proba)
  @nestAccessControl.UseRoles({
    resource: "Proba",
    action: "delete",
    possession: "any",
  })
  async deleteProba(
    @graphql.Args() args: DeleteProbaArgs
  ): Promise<Proba | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
